default_language_version:
  python: python3.10

repos:
  - repo: https://github.com/ambv/black
    rev: 18.6b4
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: detect-private-key
      - id: debug-statements
      - id: check-yaml
      - id: check-json
      - id: check-docstring-first
      - id: check-added-large-files