default_language_version:
  python: python3.8

repos:
  - repo: https://github.com/ambv/black
    rev: 18.6b4
    hooks:
      - id: black
        language_version: python3
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
      - id: flake8
      - id: trailing-whitespace
      - id: detect-private-key
      - id: debug-statements
      - id: check-yaml
      - id: check-json
      - id: check-docstring-first
      - id: check-added-large-files
  - repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
    rev: v1.0.5
    hooks:
      - id: python-bandit-vulnerability-check
        args: [./]
